# Development overrides for docker-compose.yml
# This file is automatically loaded by docker compose
# Use this for development-specific configurations

services:
  # Override bridge service for development with live reload
  bridge:
    build:
      context: ../../services/bridge
      dockerfile: Dockerfile.dev
    volumes:
      # Mount source code for live reload
      - ../../services/bridge:/app:cached
      # Exclude node_modules and other build artifacts from sync
      - /app/tmp
      - /app/logs
      # Keep persistent volumes for logs
      - bridge_logs:/app/logs
    environment:
      # Override for development
      TENNEX_BRIDGE_LOG_LEVEL: debug
      TENNEX_BRIDGE_DATABASE_URL: "postgres://tennex:tennex123@postgres:5432/tennex?sslmode=disable"
      TENNEX_BRIDGE_DEV_ENABLE_PPROF: true
      TENNEX_BRIDGE_DEV_ENABLE_METRICS: true
      TENNEX_BRIDGE_DEV_QR_IN_TERMINAL: true  # Enable for development
    # Remove healthcheck for faster startup during development
    healthcheck:
      disable: true