# Tennex Development Environment
# Docker Compose configuration for local development

services:
  # Bridge Service
  bridge:
    build:
      context: ../../services/bridge
      dockerfile: Dockerfile
    container_name: tennex-bridge
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # Application configuration
      TENNEX_BRIDGE_HTTP_PORT: 8080
      TENNEX_BRIDGE_LOG_LEVEL: debug
      
      # WhatsApp configuration
      TENNEX_BRIDGE_WHATSAPP_SESSION_PATH: /app/sessions
      TENNEX_BRIDGE_WHATSAPP_DB_LOG_LEVEL: INFO
      TENNEX_BRIDGE_WHATSAPP_HISTORY_SYNC: false
      
      # Development settings
      TENNEX_BRIDGE_DEV_ENABLE_PPROF: true
      TENNEX_BRIDGE_DEV_ENABLE_METRICS: true
      TENNEX_BRIDGE_DEV_QR_IN_TERMINAL: false  # Disabled for container
      
      # Runtime environment
      TENNEX_ENV: development
    volumes:
      - bridge_sessions:/app/sessions
      - bridge_logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  bridge_sessions:
    driver: local
  bridge_logs:
    driver: local