# Tennex Development Environment
# Docker Compose configuration for local development

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: tennex-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tennex
      POSTGRES_USER: tennex
      POSTGRES_PASSWORD: tennex123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tennex -d tennex"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Bridge Service
  bridge:
    build:
      context: ../../services/bridge
      dockerfile: Dockerfile
    container_name: tennex-bridge
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # Application configuration
      TENNEX_BRIDGE_HTTP_PORT: 8080
      TENNEX_BRIDGE_LOG_LEVEL: debug
      
      # PostgreSQL configuration for whatsmeow sessions
      TENNEX_BRIDGE_DATABASE_URL: "postgres://tennex:tennex123@postgres:5432/tennex?sslmode=disable"
      
      # WhatsApp configuration
      TENNEX_BRIDGE_WHATSAPP_DB_LOG_LEVEL: INFO
      TENNEX_BRIDGE_WHATSAPP_HISTORY_SYNC: false
      
      # Development settings
      TENNEX_BRIDGE_DEV_ENABLE_PPROF: true
      TENNEX_BRIDGE_DEV_ENABLE_METRICS: true
      TENNEX_BRIDGE_DEV_QR_IN_TERMINAL: false  # Disabled for container
      
      # Runtime environment
      TENNEX_ENV: development
    volumes:
      - bridge_logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
    driver: local
  bridge_logs:
    driver: local