# Tennex Development Environment
# Docker Compose configuration for local development

version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: tennex-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: tennex
    volumes:
      - mongodb_data:/data/db
      - ./deployments/docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - tennex-network

  # MongoDB Admin UI (optional)
  mongo-express:
    image: mongo-express:1.0.2
    container_name: tennex-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - tennex-network

  # NATS Message Queue (for future use)
  nats:
    image: nats:2.10
    container_name: tennex-nats
    restart: unless-stopped
    ports:
      - "4222:4222"  # Client connections
      - "8222:8222"  # HTTP management
    command: ["--js", "--http_port", "8222"]
    networks:
      - tennex-network

  # Bridge Service
  bridge:
    build:
      context: ./services/bridge
      dockerfile: Dockerfile
    container_name: tennex-bridge
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # Database configuration
      TENNEX_BRIDGE_MONGODB_URI: mongodb://admin:password123@mongodb:27017/tennex?authSource=admin
      TENNEX_BRIDGE_MONGODB_DATABASE: tennex
      
      # Application configuration
      TENNEX_BRIDGE_HTTP_PORT: 8080
      TENNEX_BRIDGE_LOG_LEVEL: debug
      
      # WhatsApp configuration
      TENNEX_BRIDGE_WHATSAPP_SESSION_PATH: /app/sessions
      TENNEX_BRIDGE_WHATSAPP_DB_LOG_LEVEL: INFO
      TENNEX_BRIDGE_WHATSAPP_HISTORY_SYNC: false
      
      # NATS configuration
      TENNEX_BRIDGE_NATS_URLS: nats://nats:4222
      
      # Development settings
      TENNEX_BRIDGE_DEV_ENABLE_PPROF: true
      TENNEX_BRIDGE_DEV_ENABLE_METRICS: true
      TENNEX_BRIDGE_DEV_QR_IN_TERMINAL: false  # Disabled for container
      
      # Runtime environment
      TENNEX_ENV: development
    volumes:
      - bridge_sessions:/app/sessions
      - bridge_logs:/app/logs
    depends_on:
      - mongodb
      - nats
    networks:
      - tennex-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:
    driver: local
  bridge_sessions:
    driver: local
  bridge_logs:
    driver: local

networks:
  tennex-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
