# Tennex Bridge Service Configuration

# Application settings
app_name: "tennex-bridge"
log_level: "info"  # debug, info, warn, error, fatal

# HTTP server settings
http_port: 8080

# Database settings
database_url: "postgres://tennex:tennex123@localhost:5432/tennex?sslmode=disable"

# WhatsApp client settings
whatsapp:
  db_log_level: "WARN"  # TRACE, DEBUG, INFO, WARN, ERROR
  history_sync: false
  connect_timeout: "30s"

# Development settings
dev:
  enable_pprof: true    # Enable pprof debugging endpoints
  enable_metrics: true  # Enable Prometheus metrics
  qr_in_terminal: true  # Display QR code in terminal for authentication